### PR TITLE
Save progress

### LINKED ISSUE #2: Remember progress of last played audiobook
One major problem with the app now is that you refresh the page and the player doesn't remember what the last audiobook was that you played or how far into it you progressed.

It would be great for it to remember that so that next time you return to oracy.app, it remembers what your last audiobook was, the mini player shows with that audiobook loaded, and ready to continue from the last place you listened to in the audiobook.

I'm trying to avoid a full fledged user authentication system as it's not really necessary at this point (and there's too little incentive for users to sign up). Instead, we could solve this with the use of cookies. 

So that when the user plays an audiobook, that info is saved to a cookie, and as the audiobook progresses the cookie information is updated with the latest progress marker.

Then, on Oracy page load we should first check if there is a cookie present, and if so show the mini player with the relevant information, load the appropriate track in the audiobook, and have it so that when the user clicks the play button on the player, the audiobook resumes.

### PR DESCRIPTION
**Pull request by CiprianoFreitas**
This PR adds the ability to save the progress of an audiobook on the user's devices. This uses the `localStorage` feature of browsers.

We don't have user accounts or any way to sync to different devices, but I think this is enough.

@damirkotoric take a look at this one, it's quite a big one again and some bugs might have slipped through. 

closes #2

### CODE REVIEW

**Comment by CiprianoFreitas** [comment]
What? Netlify automatically creates a link to test this PR
https://deploy-preview-11--oracy.netlify.com/

this is amazing

**Comment by CiprianoFreitas** [comment]
alright I can already see that things are not behaving correctly on my phone. I'll continue working on this

**Comment by damirkotoric** [comment]
This PR makes me feel all warm and fuzzy. With this in place we will have ourselves a product that is very minimally viable. One that I'll start using myself. I haven't spotted any bugs with it, but I am on a train without headphones, so will test better when I get home.

**Comment by damirkotoric** [comment]
https://media.giphy.com/media/BS9dyAosqbyb6/giphy.gif

**Comment by damirkotoric** [comment]
https://media.giphy.com/media/l0IykI5OLMhjtnB60/giphy.gif

**Comment by damirkotoric** [comment]
I tried putting in a GIF of Lonely Island's "Like a boss", but failed to do so because giphy serves webp images, but github can't show these. One day I will learn how to technology.

In the meantime, let me just say that your efforts are appreciated.

**Pull request merged**
