### PR TITLE
Rewrite of the app using Next.js & React

### PR DESCRIPTION
**Pull request by CiprianoFreitas**
With these changes we stop having the need for a server (at least for now) and we can deploy the app using only Netlify.
It also modularises the app to make it easier to develop.

This rewrite uses [NextJS](https://nextjs.org/) which is a framework that makes it easier to build fast react applications.

To run the app just run these commands (choose the yarn or npm versions depending on which one you use):
- `yarn` or `npm install` to install the npm packages
- `yarn dev` or `npm run dev` to start the development server (all changes in the code will update the page automatically

### CODE REVIEW

**Comment by damirkotoric** [comment]
@CiprianoFreitas All the hipster tech, love it!

So, a few things I picked up on:

**List item and player statuses can now get out of sync.**
image
When clicking play/pause from the list item, the two are in sync.
When clicking play/pause from the player, the two get out of sync.

**I assume this little thingy won't show up in prod**
image

**Would it be easy peasy to serve the audiobooks with the HTML?**
As in, how it was before adding React? If it's not a very quick n' easy task, then ignore this point. But, I figure if easy enough then why not remove that loading state altogether? Btw. I also themed the loading state there.

**Player loading state has changed**
Previous experience: you click the list item to play the audiobook, then the audio player would show in its loading state, and the audiobook would start playing when the audio loads.
Present experience: you click the list item to play the audiobook, the list item is in a loading state, and the player is hidden. Then when the audiobook loads, the player shows and starts playing instantly.
I preferred the previous experience as the UI seemed to respond more to the user feedback, and also it was clear what the next step in the experience would be. The loading state now is a bit more mysterious. What do you think about this, and would bringing back the previous experience be a lot of work?

**Is it just me, or do the audiobooks now take considerably longer to start playing?**
Could just be something to do with the archive.org servers, but the audiobooks would start more quickly before. It used to take 2-3 seconds, now it's 10+ seconds.

**UI lag**
Jan-26-2020 15-25-58
It's minuscule, and I may be overly pedantic, but it seems like there's a half a second delay in the UI updating after every click.

I'm not saying all these points have to be addressed before we merge to master, but just wanted to put it out there. When you're happy with it, feel free to merge and deploy to Netlify. Let me know if I need to point the DNS anywhere new.

Thanks for your contribution  🙌

**Review by damirkotoric — COMMENTED** [review]
@CiprianoFreitas All the hipster tech, love it!

So, a few things I picked up on:

**List item and player statuses can now get out of sync.**
image
When clicking play/pause from the list item, the two are in sync.
When clicking play/pause from the player, the two get out of sync.

**I assume this little thingy won't show up in prod**
image

**Would it be easy peasy to serve the audiobooks with the HTML?**
As in, not dynamically loading the audiobooks? If it's not a very quick n' easy task, then ignore this point. But, I figure if easy enough then why not remove that loading state altogether? Btw. I also themed the loading state there.

**Player loading state has changed**
Experience in `master`: you click the list item to play the audiobook, audio player shows up in loading state, and the audiobook plays when audio loads.
Experience in `this branch`: you click the list item to play the audiobook, the list item is in a loading state, and the player is hidden. When the audiobook loads, the player shows and starts playing instantly.

I preferred the `master` experience as the UI seemed to respond more to the user feedback, and also it was clear what the next step in the experience would be. The loading state now is a bit more mysterious. What do you think about this, and would bringing back the previous experience be a lot of work?

**The audiobooks take considerably longer to load**
On oracy.app (master) it take 1-2 seconds for the audiobooks to start playing. Now it takes 10+ seconds on this branch. This is my biggest concern out of the points listed here.

**UI lag**
Jan-26-2020 15-25-58
It's minuscule, and I may be overly pedantic, but it seems like there's a half a second delay in the UI updating after every click. The UI on master just feels more responsive.

I'm not saying all these points have to be addressed before we merge to master, but just wanted to put it out there. When you're happy with it, feel free to merge and deploy to Netlify. Let me know if I need to point the DNS anywhere new.

Thanks for your contribution  🙌

**Comment by CiprianoFreitas** [comment]
Let me fix the UI bugs before merging. We should strive for quality.
For the loading of the audiobooks, they take a long time to load on a cold start (no cache). Each file is around 8 to 11mb, after being cached they take a lot less time to load, I assume you had them cached while you were developing the app on your own so now you notice a difference. If you try to play the same audiobook now it should be fast again. But it's something to keep in mind, because they will load slow for new users.
And no, that little badge on the corner won't show up 😅

**Comment by CiprianoFreitas** [comment]
We can load the audiobooks with the html straight away. I was just keeping it like this in case in the future the list isn't static and changes over time. But for now I'll serve them right away and then we can figure out the rest.

Thanks for reviewing this. I'll fix the stuff and then we can deploy it 💪🏻

**Comment by damirkotoric** [comment]
👍

**Comment by CiprianoFreitas** [comment]
@damirkotoric give it another look. I think I've addressed all the things you mentioned. And even managed to improve the audio loading time. 
You were totally right, you had a configuration in the howler library that allows it to stream the audio before loading the entire file. One day you'll be teaching me javascript, good catch.
Anyway, I've coding away for a couple of hours so a pair of fresh eyes might notice something I've missed.
After your approval I'll take care of the merge conflicts and deploy to netlify.

**Review by damirkotoric — APPROVED** [review]
Looks good to me! 🎉 

I've been a bit under the pump with new freelance work so took me a while to respond. Full speed ahead now.

**Pull request merged**
